plugins {
    id("java")
    id("base")
}

group "com.thisisjairajwani"
description "This project contains the solution of problems that I attempt on LeetCode and practical implementation of topics I learn related to Java, Gradle and other things"
version = "1.0-SNAPSHOT"

defaultTasks 'test'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.test {
    useJUnitPlatform()
}

tasks.register("archiveFiles", Zip) {
    group 'Java Learning'
    description 'Compresses the src directory into a zip file'
    archiveBaseName = "srcZip"
    from("src/main/java")
    setDestinationDirectory(new File("./build/archives"))
}

tasks.register('exampleTask') {
    doLast {
        println 'do last'
    }
    doFirst {
        println 'do first'
    }
}